# Generated by Django 3.1.3 on 2020-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('team_color', models.CharField(default='white', max_length=30)),
                ('total_matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('nrr', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-points', '-nrr'],
            },
        ),
    ]
